---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-{{ .Release.Name }}
  labels:
    app: backend-{{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: backend-{{ .Release.Name }}
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: backend-{{ .Release.Name }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.images.imagepullsecret | quote }}

      initContainers:
        - name: wait-for-redis
          image: {{ .Values.images.init.check_redis_available.image | quote }}
          args: [ 'sh', '-c', 'until redis-cli  -h redis -p 6379  get hello; do echo "Sleeping a bit"; sleep 1; done; echo "ready!"; ' ]

      volumes:
        - name: config-volume
          configMap:
            name: tower-yml-{{ .Release.Name }}
        - name: cert-volume
          secret:
            secretName: {{ .Values.cm.platform.tower_oidc_pem_secret_name }}
  
      containers:
        - name: backend
          image: {{ .Values.images.backend.main.image | quote }}
          envFrom:
            - configMapRef:
                name: tower-backend-cfg-{{ .Release.Name }}
          env:
            - name: MICRONAUT_ENVIRONMENTS
              value: "prod,redis,ha"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config-volume
              mountPath: /tower.yml
              subPath: tower.yml
            - name: cert-volume
              mountPath: /data/certs/oidc.pem
              subPath: tls.key
             
          resources:
            requests:
              cpu: {{ .Values.resources.backend.cpu.request | quote }}
              memory: {{ .Values.resources.backend.memory.request | quote }}
            limits:
              memory: {{ .Values.resources.backend.memory.limit | quote }}
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 3
            failureThreshold: 10
          command: [ "/bin/sh" ]
          # args:
          #   - -c
          #   - | 
          #       keytool -printcert -rfc -sslserver csgitlab2.dev-seqera.net:443  >  /PRIVATE_CERT.pem; 
          #       keytool -import -trustcacerts -cacerts -storepass changeit -noprompt -alias graham -file /PRIVATE_CERT.pem ; 
          #       ./tower.sh
          args:
            - -c
            - |  
                ./tower.sh

---
apiVersion: v1
kind: Service
metadata:
  name: backend-{{ .Release.Name }}
  labels:
    app: backend-{{ .Release.Name }}
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: backend-{{ .Release.Name }}

---
apiVersion: v1
kind: Service
metadata:
  name: backend-api-{{ .Release.Name }}
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: NodePort
  selector:
    app: backend-{{ .Release.Name }}