---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: connect-server
  labels:
    app.kubernetes.io/component: connect-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: connect-server
  serviceName: connect-server
  template:
    metadata:
      labels:
        app.kubernetes.io/component: connect-server
    spec:
      imagePullSecrets:
        - name: {{ .Values.images.imagepullsecret | quote }}
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
        - name: server
          image: {{ .Values.images.connectserver.main.image | quote }}
          ports:
            - containerPort: {{.Values.config.connect.CONNECT_TUNNEL_PORT }}
              name: server
            - containerPort: {{ .Values.config.connect.CONNECT_LISTENER_PORT }}
              name: entrypoint
          env:
            - name: CONNECT_HOST_DOMAIN
              value: {{ .Values.config.connect.CONNECT_HOST_DOMAIN | quote }}
            - name: CONNECT_TUNNEL_PORT
              value: {{ .Values.config.connect.CONNECT_TUNNEL_PORT | quote }}
            - name: CONNECT_LISTENER_PORT
              value: {{ .Values.config.connect.CONNECT_LISTENER_PORT | quote }}
            - name: CONNECT_REDIS_ADDRESS
              value: {{ printf "%s:%s" .Values.cm.platform.redis_host .Values.cm.platform.redis_port | quote }}
            - name: CONNECT_REDIS_PREFIX
              value: "connect:session"
            - name: CONNECT_REDIS_TLS_ENABLE
              value: {{ .Values.config.connect.CONNECT_REDIS_TLS_ENABLE | quote }}
            - name: CONNECT_REDIS_DB
              value: {{ .Values.config.connect.CONNECT_REDIS_DB | quote }}
            - name: CONNECT_SERVER_LOG_LEVEL
              value: {{ .Values.config.connect.CONNECT_SERVER_LOG_LEVEL | quote }}
---
apiVersion: v1
kind: Service
metadata:
  name: connect-server
  labels:
    app.kubernetes.io/component: connect-server
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.config.connect.server_service_port }}
      targetPort: server
      name: server

    - port: {{ .Values.config.connect.CONNECT_LISTENER_PORT }}
      targetPort: entrypoint
      name: entrypoint
  selector:
    app.kubernetes.io/component: connect-server
