apiVersion: apps/v1
kind: Deployment
metadata:
  name: connect-proxy
  labels:
    app.kubernetes.io/component: connect-proxy
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: connect-proxy
  template:
    metadata:
      labels:
        app.kubernetes.io/component: connect-proxy
    spec:
      imagePullSecrets:
        - name: {{.Values.images.imagepullsecret | quote}}
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
        - name: proxy
          image: {{.Values.images.connectproxy.main.image | quote}}
          # command: ["caddy", "serve"]  # Removed
          env:
            # IMO this is confusing. These should be pushed to the ConfigMap and centralized.
            # NOTE: Disable YAML format on save so these dont get messed up.
            - name: PLATFORM_URL
              value: {{ .Values.cm.platform.TOWER_SERVER_URL | quote }}
            - name: CONNECT_HTTP_PORT
              value: {{ .Values.config.connect.CONNECT_HTTP_PORT | quote }}
            - name: CONNECT_REDIS_ADDRESS
              value: {{ printf "%s:%s" .Values.cm.platform.redis_host .Values.cm.platform.redis_port | quote }}
            - name: CONNECT_REDIS_PREFIX
              value: "connect:session"
            - name: CONNECT_REDIS_TLS_ENABLE
              value: {{ .Values.config.connect.CONNECT_REDIS_TLS_ENABLE | quote }}
            - name: CONNECT_REDIS_DB
              value: {{ .Values.config.connect.CONNECT_REDIS_DB | quote }}
            - name: CONNECT_PROXY_URL
              value: {{ .Values.cm.platform.TOWER_DATA_STUDIO_CONNECT_URL | quote }}
            - name: CONNECT_TUNNEL_URL
              value: {{ .Values.config.connect.CONNECT_TUNNEL_URL | quote }}
            - name: CONNECT_OIDC_CLIENT_REGISTRATION_TOKEN
              value: {{ .Values.cm.platform.TOWER_OIDC_REGISTRATION_INITIAL_ACCESS_TOKEN | quote }}
            - name: LOCAL_CACHE_TTL
              value: "2m"
            # Extra stuff Sushma has https://github.com/seqeralabs/connect/blob/master/docs/features/ssh.md?plain=1
            - name: CONNECT_SSH_ENABLED
              value: {{ .Values.config.connect.CONNECT_SSH_ENABLED | quote }}
            - name: CONNECT_SSH_ADDR
              value: {{ .Values.config.connect.CONNECT_SSH_ADDR | quote }}
            # - name: CONNECT_SSH_KEY_PATH  -- I dont set fingerprint
            #   value: "/secrets/ssh-key"
          # nEW MANIFEST HAS securityContext stuff
          ports:
            - containerPort: {{ .Values.config.connect.CONNECT_HTTP_PORT }}
              name: proxy
---
apiVersion: v1
kind: Service
metadata:
  name: connect-proxy
  labels:
    app.kubernetes.io/component: connect-proxy
spec:
  type: NodePort
  ports:
    - port: 80
      name: connect-proxy
      targetPort: proxy
  selector:
    app.kubernetes.io/component: connect-proxy
---
# NLB uses "IP target type", so flow is: NLB → Pod IP (10.1.103.55) directly via VPC routing
# Access controlled by Node's security group (port 2222) -- added to cx-solo via ssh phase.
apiVersion: v1
kind: Service
metadata:
  name: connect-proxy-ssh
  labels:
    app.kubernetes.io/component: connect-proxy
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: {{.Values.config.connectsshservice.nlb_type | quote}}
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    service.beta.kubernetes.io/aws-load-balancer-scheme: {{.Values.config.connectsshservice.nlb_scheme | quote}}
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.cm.platform.TOWER_DATA_STUDIO_CONNECT_SSH_ADDRESS | trimPrefix "https://" | quote }}
spec:
  type: LoadBalancer
  ports:
    - name: ssh
      port: {{.Values.cm.platform.TOWER_DATA_STUDIO_CONNECT_SSH_PORT}}
      targetPort: {{.Values.cm.platform.TOWER_DATA_STUDIO_CONNECT_SSH_PORT}}
      protocol: TCP
  selector:
    app.kubernetes.io/component: connect-proxy
