---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cron-{{ .Release.Name }}
  labels:
    app: cron-{{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: cron-{{ .Release.Name }}
  template:
    metadata:
      labels:
        app: cron-{{ .Release.Name }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.images.imagepullsecret | quote }}

      volumes:
        - name: config-volume
          configMap:
            name: tower-yml-{{ .Release.Name }}
        - name: cert-volume
          secret:
            secretName: {{ .Values.cm.platform.tower_oidc_pem_secret_name }}

      initContainers:
        - name: 01-migrate-db
          image: {{ .Values.images.cron.init.migration_image | quote }}
          command: ["sh", "-c", "/migrate-db.sh"]
          envFrom:
            - configMapRef:
                name: tower-backend-cfg-{{ .Release.Name }}
          volumeMounts:
            - name: config-volume
              mountPath: /tower.yml
              subPath: tower.yml

        - name: 02-wait-for-redis
          image: {{ .Values.images.init.check_redis_available.image | quote}}
          #args: [ 'sh', '-c', 'until redis-cli  -h redis.default.svc.cluster.local -p 6379  get hello; do echo "..."; ' ]
          args: [ 'sh', '-c', 'until redis-cli  -h redis -p 6379  get hello; do echo "Sleeping a bit"; sleep 1; done; echo "ready!"; ' ]

        - name: 03-wait-for-ingress
          image: {{ .Values.images.init.check_ingress_available.image | quote}}
          #args: [ 'sh', '-c', 'until redis-cli  -h redis.default.svc.cluster.local -p 6379  get hello; do echo "Sleeping a bit"; sleep 1; done; echo "ready!"; ' ]
          # args: [ 'sh', '-c', "while [[ \"$(curl https://gw.dev-tower.net -s -o /dev/null -L -w ''%{http_code}'' ${0})\" != \"200\" ]]; do echo 'sleep 2'; sleep 2; done; echo \"I made it out of the loop\";" ]
          # Tried curling ingress, not working. Now just doing plain sleep.
          args: [ 'sh', '-c', 'sleep 30' ]

      containers:
        - name: backend
          image: {{ .Values.images.cron.main.image | quote }}
          envFrom:
            - configMapRef:
                name: tower-backend-cfg-{{ .Release.Name }}
          volumeMounts:
            - name: config-volume
              mountPath: /tower.yml
              subPath: tower.yml
            - name: cert-volume
              mountPath: /data/certs/oidc.pem
              subPath: tls.key
          env:
            - name: MICRONAUT_ENVIRONMENTS
              value: "prod,redis,cron"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 3
            failureThreshold: 10