---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-frontend
  labels:
    app: {{ .Release.Name }}-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-frontend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-frontend
    spec:
# {{/*- include "ktower.imagepullsecret" . | indent 6 */}}
      imagePullSecrets:
        - name: {{ .Values.images.imagepullsecret | quote }}
      containers:
        - name: frontend
          {{- with .Values.images.frontend.main }}
          # image: cr.seqera.io/private/nf-tower-enterprise/frontend:v22.4.2
          image: {{ printf "%s:%s" .image .tag | quote }}
          imagePullPolicy: {{ .pullpolicy | quote }}
          {{- end }}
          command: [ "/bin/sh" ]
          args: [ "-c", "sed -i 's/backend:8080/{{ .Release.Name }}-backend:8080/g' /etc/nginx/nginx.conf && nginx -g 'daemon off;'" ]
          ports:
            - containerPort: {{ .Values.images.frontend.main.port }} # 80
          env:
            - name: NGINX_HOST
              value: "{{ .Release.Name }}-backend"
            - name: NGINX_PORT
              value: "{{ .Values.images.frontend.main.port }}"
        
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-frontend
  annotations: 
    oci.oraclecloud.com/load-balancer-type: "lb"
    service.beta.kubernetes.io/oci-load-balancer-shape: "flexible"
    service.beta.kubernetes.io/oci-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/oci-load-balancer-tls-secret: "seqera/tls-secret"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: "10"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: "100"
    service.beta.kubernetes.io/oci-load-balancer-backend-protocol: "HTTP"
    service.beta.kubernetes.io/oci-load-balancer-security-list-management-mode: "All"  #"None"
    oci.oraclecloud.com/oci-network-security-groups: "ocid1.networksecuritygroup.oc1.iad.aaaaaaaano5jocxetxfxfbcsnd7ukpha6mmey7tvkjd36vwej6wgkfopfflq"
    oci.oraclecloud.com/node-label-selector: nodepooltype=seqerapool
spec:
  type: LoadBalancer
  ports:
  - name: https
    port: 443
    targetPort: 80
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: {{ .Release.Name }}-frontend
---