apiVersion: v2
name: oracle-tower
description: Helm Chart to install Nextflow Tower
version: "0.1"
type: application
# icon: https://salaboy.files.wordpress.com/2019/07/avatar.png
appVersion: "24.1"
maintainers: 
  - name: gwright99
    email: graham.wright@seqera.io
    url: https://github.com/gwright99/
home: http://github.com/gwright99/tower
keywords:
  - cloudnative
  - example
  - helm
  - kubernetes
  - tutorial