apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: plainnginx
  name: plainnginx
  namespace: default
spec:
  containers:
  - image: nginx:latest
    name: plainnginx
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
