apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: plainnginx
    foo: bar
  name: plainnginx
  # namespace: default
  namespace: argocd
spec:
  containers:
  - image: nginx:latest
    name: plainnginx
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
