apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: plain_nginx
  name: plain_nginx
  namespace: default
spec:
  containers:
  - image: nginx:latest
    name: plain_nginx
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
