apiVersion: v2
name: nextflow-tower
description: Helm Chart to install Nextflow Tower
version: 0.1.18
type: application
# icon: https://salaboy.files.wordpress.com/2019/07/avatar.png
appVersion: 22.4.2
maintainers: 
  - name: gwright99
    email: graham.wright@seqera.io
    url: https://github.com/gwright99/
home: http://github.com/gwright99/tower
keywords:
  - cloudnative
  - example
  - helm
  - kubernetes
  - tutorial
#dependencies:
#- name: postgresql
#  repository: https://charts.bitnami.com/bitnami
#  version: 10.8.0 
dependencies:
- name:           mysql
  repository:     https://charts.bitnami.com/bitnami
  version:        8.0.32
#a