apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: plainnginx3
  name: plainnginx3
  namespace: default
spec:
  containers:
  - image: nginx:latest
    name: plainnginx3
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: plainnginx3
  name: plainnginx3
  namespace: default
spec:
  containers:
  - image: nginx:latest
    name: plainnginx3
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}