apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: localstack
  finalizers:
  # - resources-finalizer.argocd.argoproj.io
  - resources-finalizer.argocd.argoproj.io/background
spec:
  project: default
  source:
    repoURL: https://github.com/gwright99/aws_localstack.git
    path: manifests/
    targetRevision: HEAD
    directory:
      recurse: true
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      # selfHeal: true
      prune: true           # Delete and replace
      # replace: true        # Causes outOfSync issues