apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  finalizers:
  # - resources-finalizer.argocd.argoproj.io
  - resources-finalizer.argocd.argoproj.io/background
spec:
  # project: default
  # project: argocd
  source:
    repoURL: https://github.com/gwright99/ci_cd_for_k8s.git
    # Knows it's a Helm app if it finds Chart.yaml under the `path`.
    path: charts/root-app/
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true