apiVersion: v2
name: nextflow-tower-25-3-4
description: Helm Chart to install Seqera Platform
version: "0.02"
type: application
appVersion: "25.3.4"
maintainers:
  - name: gwright99
    email: graham.wright@seqera.io
    url: https://github.com/gwright99/
home: http://github.com/gwright99/tower
keywords:
  - cloudnative
  - helm
  - kubernetes
  - Seqera Platform

# DECISION - Mar 21/23 - the inclusion of subcharts is more troublesome than it initially appears useful.
# Idea is to deploy MySQL separately first and then deploy Tower afterwards, after manual customization.
# dependencies:
# - name:           mysql
#   repository:     "https://charts.bitnami.com/bitnami"
#   version:        "9.6.0"  # mysqlv8.0.32
#   condition: mysql.enabled
