apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: plainnginx2
  name: plainnginx2
  namespace: default
spec:
  containers:
  - image: nginx:latest
    name: plainnginx2
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
