---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      # imagePullSecrets:
      #   - name: {{ .Values.images.imagepullsecret | quote }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      containers:
        - name: slurm
          {{- with .Values.images.slurm.main }}
          image: {{ printf "%s:%s" .image .tag }}
          {{- end }}
          env:
            - name: TOWER_ACCESS_TOKEN
              value: {{ .Values.config.TOWER_ACCESS_TOKEN }}
            - name: TOWER_API_ENDPOINT
              value: {{ .Values.config.TOWER_API_ENDPOINT }}
            - name: AGENT_CONNECTION_ID
              value: {{ .Values.config.AGENT_CONNECTION_ID }}
          ports:
            - containerPort: 22
          resources:
            requests:
              cpu: {{ .Values.resources.slurm.cpu.request | quote }}
              memory: {{ .Values.resources.slurm.memory.request | quote }}
            limits:
              memory: {{ .Values.resources.slurm.memory.limit | quote }}
          command: ["/bin/bash"]
          args: ["-c", "service munge start && service slurmctld start && service slurmd start  && cd /home  && LOGGER_LEVELS_IO_SEQERA_TOWER_AGENT=TRACE ./tw-agent $AGENT_CONNECTION_ID -u $TOWER_API_ENDPOINT --work-dir=."]
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  ports:
    - name: ssh
      protocol: TCP
      port: 22
      targetPort: 22
  type: NodePort
  selector:
    app: {{ .Release.Name }}