---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      # imagePullSecrets:
      #   - name: {{ .Values.images.imagepullsecret | quote }}

      containers:
        - name: xenon
          {{- with .Values.images.xenon.main }}
          image: {{ printf "%s:%s" .image .tag }}
          {{- end }}
          env:
            - name: TOWER_ACCESS_TOKEN
              value: {{ .Values.config.TOWER_ACCESS_TOKEN }}
            - name: TOWER_API_ENDPOINT
              value: {{ .Values.config.TOWER_API_ENDPOINT }}
            - name: TOWER_AGENT_CREDENTIAL_ID
              value: {{ .Values.config.TOWER_AGENT_CREDENTIAL_ID }}
          ports:
            - containerPort: 22

          resources:
            requests:
              cpu: {{ .Values.resources.xenon.cpu.request | quote }}
              memory: {{ .Values.resources.xenon.memory.request | quote }}
            limits:
              memory: {{ .Values.resources.xenon.memory.limit | quote }}
          # readinessProbe:
          #   httpGet:
          #     path: /health
          #     port: 8080
          #   initialDelaySeconds: 5
          #   timeoutSeconds: 3
          # livenessProbe:
          #   httpGet:
          #     path: /health
          #     port: 8080
          #   initialDelaySeconds: 5
          #   timeoutSeconds: 3
          #   failureThreshold: 10

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  ports:
    - name: ssh
      port: 22
      targetPort: 22
  selector:
    app: {{ .Release.Name }}