# To override dependency chart values, must use a top-level key matching the dependency chart's name (in Chart.yaml).
# Original Helm chart values can be found here: [https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/values.yaml](https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/values.yaml)

argo-cd:
  # integration with external auth providers
  dex:
    enabled: false
  # notify users about changes to application state
  notifications:
    enabled: false
  # automated generation of Argo CD Applications
  applicationSet:
    enabled: false
  # serve the Web UI over HTTP without TLS
  server:
    extraArgs:
      - --insecure