---
kind: ConfigMap
apiVersion: v1
metadata:
  name: tower-backend-cfg
  labels:
    app: backend-cfg
data:
  TOWER_SERVER_URL:        {{ .Values.config.TOWER_SERVER_URL }}
  TOWER_CONTACT_EMAIL:     {{ .Values.config.TOWER_CONTACT_EMAIL }}
  TOWER_JWT_SECRET:        {{ .Values.config.TOWER_JWT_SECRET }}
  TOWER_CRYPTO_SECRETKEY:  {{ .Values.config.TOWER_CRYPTO_SECRETKEY }}
  TOWER_LICENSE:           {{ .Values.config.TOWER_LICENSE }}
  TOWER_ENABLE_PLATFORMS:  "awsbatch-platform,slurm-platform"

  TOWER_DB_URL: {{ .Values.config.TOWER_DB_URL }}
  TOWER_DB_DRIVER: "org.mariadb.jdbc.Driver"
  TOWER_DB_USER: "tower"
  TOWER_DB_PASSWORD: {{ .Values.config.TOWER_DB_PASSWORD }}
  TOWER_DB_DIALECT: "io.seqera.util.MySQL55DialectCollateBin"
  TOWER_DB_MIN_POOL_SIZE: "2"
  TOWER_DB_MAX_POOL_SIZE: "10"
  TOWER_DB_MAX_LIFETIME: "180000"
  FLYWAY_LOCATIONS: "classpath:db-schema/mysql"

  TOWER_SMTP_HOST:      {{ .Values.config.TOWER_SMTP_HOST }}
  TOWER_SMTP_PORT:      "{{ .Values.config.TOWER_SMTP_PORT }}"
  TOWER_SMTP_USER:      {{ .Values.config.TOWER_SMTP_USER }}
  TOWER_SMTP_PASSWORD:  {{ .Values.config.TOWER_SMTP_PASSWORD }}

  TOWER_REDIS_URL:      {{ .Values.config.TOWER_REDIS_URL }}
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: tower-yml
  labels:
    app: backend-cfg
data:
  tower.yml: |
    mail:
      smtp:
        # FIXME `auth` and `starttls` should be enabled
        # with a production SMTP host
        auth: false
        starttls:
          enable: false
          required: false