apiVersion: apps/v1
kind: Deployment
metadata:
  name: connect-proxy
  labels:
    app.kubernetes.io/component: tower-connect-proxy
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: tower-connect-proxy
  template:
    metadata:
      labels:
        app.kubernetes.io/component: tower-connect-proxy
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
        - name: proxy
          image: cr.seqera.io/private/nf-tower-enterprise/data-studio/connect-proxy:0.7.0
          command:
            - serve
          env:
            - name: CONNECT_HTTP_PORT
              value: {{ .Values.config.CONNECT_HTTP_PORT }}  # "80"
              # "hostname.domain.cache.amazonaws.com:6379"
            - name: CONNECT_REDIS_ADDRESS
              value: {{ .Values.redis.TOWER_REDIS_URL }}
            - name: CONNECT_REDIS_PREFIX
              value: "connect:session"
            - name: CONNECT_REDIS_TLS_ENABLE
              value: {{ .Values.redis.CONNECT_REDIS_TLS_ENABLE }}
            - name: CONNECT_REDIS_DB
              value: "{{ .Values.redis.CONNECT_REDIS_DB }}"
            - name: CONNECT_PROXY_URL
              value: {{ .Values.redis.TOWER_DATA_STUDIO_CONNECT_URL }}
            - name: CONNECT_TUNNEL_URL
              value: {{ .Values.redis.CONNECT_TUNNEL_URL }}  #connect-server:7070
            - name: PLATFORM_URL
              value: {{ .Values.redis.TOWER_SERVER_URL }}
            - name: CONNECT_OIDC_CLIENT_REGISTRATION_TOKEN
              valueFrom:
                secretKeyRef:
                  name: connect-proxy-secret
                  key: OIDC_CLIENT_REGISTRATION_TOKEN
            - name: LOCAL_CACHE_TTL
              value: 2m
          ports:
            - containerPort: 80
              name: proxy
---
apiVersion: v1
kind: Service
metadata:
  name: connect-proxy
  labels:
    app.kubernetes.io/component: tower-connect-proxy
spec:
  type: NodePort
  ports:
    - port: 80
      name: connect-proxy
      targetPort: proxy
  selector:
    app.kubernetes.io/component: tower-connect-proxy
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: connect-server
  labels:
    app.kubernetes.io/component: connect-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/component: connect-server
  serviceName: connect-server
  template:
    metadata:
      labels:
        app.kubernetes.io/component: connect-server
    spec:
      nodeSelector: 
        kubernetes.io/arch: amd64
      containers:
        - name: server
          image: cr.seqera.io/private/nf-tower-enterprise/data-studio/connect-server:0.7.0
          ports:
            - containerPort: 7070
              name: server
            - containerPort: 7777
              name: entrypoint
          env:
            - name: CONNECT_HOST_DOMAIN
              value: connect-server
            - name: CONNECT_TUNNEL_PORT
              value: "7070"
            - name: CONNECT_LISTENER_PORT
              value: "7777"
            - name: CONNECT_REDIS_ADDRESS
              value: {{ .Values.redis.TOWER_REDIS_URL }}
            - name: CONNECT_REDIS_PREFIX
              value: connect:session
            - name: CONNECT_REDIS_TLS_ENABLE
              value: {{ .Values.redis.CONNECT_REDIS_TLS_ENABLE }}
            - name: CONNECT_REDIS_DB
              value: "{{ .Values.redis.CONNECT_REDIS_DB }}"
            - name: CONNECT_SERVER_LOG_LEVEL
              value: {{ .Values.redis.CONNECT_SERVER_LOG_LEVEL }}
---
apiVersion: v1
kind: Service
metadata:
  name: connect-server
  labels:
    app.kubernetes.io/component: connect-server
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 8080
      targetPort: server
      name: server
    - port: 7777
      targetPort: entrypoint
      name: entrypoint
  selector:
    app.kubernetes.io/component: connect-server