{{- $cert := genSelfSignedCertWithKey "" (list) (list) 3650 (genPrivateKey "rsa") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.config.TOWER_OIDC_PEM_SECRET_NAME }}
type: kubernetes.io/tls
data:
  tls.crt: |
    {{ $cert.Cert | b64enc }}
  tls.key: |
    {{ $cert.Key | b64enc }}