---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: connect-server
  labels:
    app.kubernetes.io/component: connect-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: connect-server
  serviceName: connect-server
  template:
    metadata:
      labels:
        app.kubernetes.io/component: connect-server
    spec:
      imagePullSecrets:
        - name: {{ .Values.images.imagepullsecret | quote }}
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
        - name: server
          {{- with .Values.images.connectserver.main }}
          image: {{ printf "%s:%s" .image .tag | quote }}
          {{- end }}
          ports:
            - containerPort: 7070
              name: server
            - containerPort: 7777
              name: entrypoint
          env:
            - name: CONNECT_HOST_DOMAIN
              value: connect-server
            - name: CONNECT_TUNNEL_PORT
              value: "7070"
            - name: CONNECT_LISTENER_PORT
              value: "7777"
            - name: CONNECT_REDIS_ADDRESS
              value: {{ .Values.config.TOWER_REDIS_URL | trimPrefix "redis://" | quote }}
            - name: CONNECT_REDIS_PREFIX
              value: connect:session
            - name: CONNECT_REDIS_TLS_ENABLE
              value: "{{ .Values.config.CONNECT_REDIS_TLS_ENABLE }}"
            - name: CONNECT_REDIS_DB
              value: "{{ .Values.config.CONNECT_REDIS_DB }}"
            - name: CONNECT_SERVER_LOG_LEVEL
              value: "{{ .Values.config.CONNECT_SERVER_LOG_LEVEL }}"
---
apiVersion: v1
kind: Service
metadata:
  name: connect-server
  labels:
    app.kubernetes.io/component: connect-server
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    # dont 100% recall why this is the way that it is
    - port: 8080
      targetPort: server
      name: server
    - port: 7777
      targetPort: entrypoint
      name: entrypoint
  selector:
    app.kubernetes.io/component: connect-server
