---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-frontend
  labels:
    app: {{ .Release.Name }}-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-frontend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-frontend
    spec:
# {{/*- include "ktower.imagepullsecret" . | indent 6 */}}
      imagePullSecrets:
        - name: {{ .Values.images.imagepullsecret | quote }}
      containers:
        - name: frontend
          {{- with .Values.images.frontend.main }}
          image: {{ printf "%s:%s" .image .tag | quote }}
          imagePullPolicy: {{ .pullpolicy | quote }}
          {{- end }}
          
          command: [ "/bin/sh" ]
          args: [ "-c", "sed -i 's/backend:8080/{{ .Release.Name }}-backend:8080/g' /etc/nginx/nginx.conf && nginx -g 'daemon off;'" ]
          ports:
            - containerPort: {{ .Values.images.frontend.main.port }} # 80
          env:
            - name: NGINX_HOST
              value: "{{ .Release.Name }}-backend"
            - name: NGINX_PORT
              value: "{{ .Values.images.frontend.main.port }}"
        
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-frontend
spec:
  # type: LoadBalancer
  type: NodePort
  ports:
    - port: 80 # {{ .Values.images.frontend.main.port }} # 80
  selector:
    app: {{ .Release.Name }}-frontend