# Need to provision on PV and 2 PVCs (both pointing to same PV) so we can isolate the Wave Build activity
# to its own namespace, but still be able to let the main Wave pod monitor what's going on (via filesytem).
---
# Assumption: Storage dynamically provisioned using AWS EFS CSI driver
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{.Values.wave.storage_class.name | quote}}
provisioner: {{.Values.wave.storage_class.csi_provisioner | quote}}
parameters:
  provisioningMode: {{.Values.wave.storage_class.provisioning_mode | quote}}
  # fileSystemId: {{.Values.wave.storage_class.filesystem_id | quote}}
  # directoryPerms: "700"
# reclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{.Values.wave.filesystem.app.pv_name | quote}}
spec:
  capacity:
    storage: {{.Values.wave.filesystem.app.size | quote}}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{.Values.wave.storage_class.name | quote}}
  csi:
    driver: {{.Values.wave.storage_class.csi_provisioner | quote}}
    # volumeHandle: {{.Values.wave.storage_class.csi_volume_handle | quote}}
    volumeHandle: {{.Values.wave.storage_class.filesystem_id | quote}}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{.Values.wave.filesystem.build.pv_name | quote}}
spec:
  capacity:
    storage: {{.Values.wave.filesystem.build.size | quote}}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{.Values.wave.storage_class.name | quote}}
  csi:
    driver: {{.Values.wave.storage_class.csi_provisioner | quote}}
    # volumeHandle: {{.Values.wave.storage_class.csi_volume_handle | quote}}
    volumeHandle: {{.Values.wave.storage_class.filesystem_id | quote}}
---
# These two PVCs must be separate but need to be linked under the hood (I've used 'pv_size' to keep synced)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{.Values.wave.app.namespace | quote}}
  name: {{.Values.wave.filesystem.app.pvc_name | quote}}
  labels:
    app: {{.Values.wave.app.app_name | quote}}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{.Values.wave.filesystem.app.size | quote}}
  storageClassName: {{.Values.wave.storage_class.name | quote}}
  volumeName: {{.Values.wave.filesystem.app.pv_name | quote}} # NEW
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{.Values.wave.build.namespace | quote}}
  name: {{.Values.wave.filesystem.build.pvc_name | quote}}
  labels:
    app: {{.Values.wave.app.app_name | quote}}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{.Values.wave.filesystem.build.size | quote}}
  storageClassName: {{.Values.wave.storage_class.name | quote}}
  volumeName: {{.Values.wave.filesystem.build.pv_name | quote}} # NEW
