# Source: https://helm.sh/docs/howto/chart_releaser_action/
name: Release Charts

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'charts/root-app/**'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        # uses: actions/checkout@v3  # Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      # ArgoCD dependency throws error:
      # "Error: no repository definition for https://argoproj.github.io/argo-helm"
      # If you don't install the dependency chart first.
      # See: https://github.com/helm/chart-releaser-action/issues/74#issuecomment-1206111172
      - name: Add Helm repo dependencies
        run: |
          for dir in $(ls -d charts/*/); do
            helm dependency list $dir 2> /dev/null | tail +2 | head -n -1 | awk '{ print "helm repo add " $1 " " $3 }' | while read cmd; do $cmd; done
          done

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
